#!/usr/bin/env node
// Regenerate the pack pixel art: `node scripts/pixel-art.mjs [pack…]`.
//
// The drawings live in art/<pack>.mjs (palettes, text-grid sprites and
// shaded iso boxes, on top of art/lib.mjs); this writes them as SVGs on the
// 2 px art-pixel grid to packs/<pack>/assets/. `--preview out.png` also
// writes an enlarged contact sheet of every image
// (`--only <regex>` limits it to matching file names, drawn larger). See docs/art.md.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { contactSheet, toSvg } from '../art/lib.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PACKS = ['std', 'zombie', 'vampire', 'garden'];

const args = process.argv.slice(2);
const p = args.indexOf('--preview');
const preview = p >= 0 ? args.splice(p, 2)[1] : null;
const o = args.indexOf('--only');
const only = o >= 0 ? new RegExp(args.splice(o, 2)[1]) : null;
const packs = args.length ? args : PACKS;

const sheet = [];
for (const pack of packs) {
  if (!PACKS.includes(pack)) throw new Error(`unknown pack '${pack}' (have ${PACKS.join(', ')})`);
  const { palette, images } = await import(`../art/${pack}.mjs`);
  const dir = resolve(root, 'packs', pack, 'assets');
  mkdirSync(dir, { recursive: true });
  for (const { file, canvas, note } of images()) {
    const comment = `generated by scripts/pixel-art.mjs from art/${pack}.mjs${note ? `; ${note}` : ''}`;
    writeFileSync(resolve(dir, file), toSvg(canvas, palette, comment));
    if (!only || only.test(file)) sheet.push({ c: canvas, palette });
  }
  console.log(`packs/${pack}/assets: ${images().length} images`);
}
if (preview) {
  writeFileSync(preview, contactSheet(sheet, only ? 8 : 4, only ? 6 : 8));
  console.log(`preview: ${preview}`);
}
